name: Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install -g firebase-tools
        
      - name: Deploy to Staging
        if: github.event_name == 'pull_request'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use staging
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"
          
      - name: Deploy to Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use production
          firebase deploy --only hosting --token "$FIREBASE_TOKEN" 